package mini4sem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shree raksha
 */
public class Signup_Page extends javax.swing.JFrame {
int id =0;
    /**
     * Creates new form Signup_Page
     */String fname,lname,uname,password,con_pass,contact_no;
    public Signup_Page() {
        initComponents();
      
    }
   /* public int getId(){
        ResultSet rs = null ;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://localhost/sem4mini","root",""); 
            String sql ="select max(id) from sign_up" ;
            PreparedStatement ps = con.prepareStatement(sql);
            Statement st = con.createStatement();
            rs =  st.executeQuery(sql);
            while(rs.next()){
                id++;
                id = rs.getInt(1);
            }
            
            
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
        return id;
    }*/
    boolean validation()
    {
       
        
        fname=txt_firstname.getText();
        lname=txt_lastname.getText();
        uname=txt_username.getText();
        password=txt_password.getText();
        con_pass=txt_confirmpassword.getText();
        contact_no=txt_contactnumber.getText();
        
        if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter firstname");
            return false;
        }
        
        if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter lastname");
            return false;
        }
        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter username");
            return false;
        }
        if(password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter password");
            return false;
        }
        if(con_pass.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter confirmpassword");
            return false;
        }
        if(contact_no.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter contactnumber");
            return false;
        }
        if (password.length()<8)
        {
         lbl_password_error.setText("password should be 8 digits");
        }
        if(!password.equals(con_pass))
        {
           JOptionPane.showMessageDialog(this,"passwordnot matched");
           return false;
        }
        return true;
    }
    public void checkPassword()
    {
        password=txt_password.getText();
        if(password.length()<8){
            lbl_password_error.setText("password should be of 8 digits");
        }
        else
        {
           lbl_password_error.setText(" ");
        }
    }
   /* public void checkContactNo()
    {
         contact_no=txt_contactnumber.getText();
        if (contact_no.length()==10)
        {
            lbl_contact_error.setText("");
        }
        else
        {
            lbl_contact_error.setText("Contact no should be of 10 digits");
        }
    }*/
    
    void insertDetails(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://localhost/employeedetails","root",""); 
            String sql ="insert into signup(fname,lname,uname,password,contact_no) values(?,?,?,?,?)" ;
            PreparedStatement ps = con.prepareStatement(sql);
           // ps.setInt(1,getId());
            ps.setString(1,fname);
            ps.setString(2, lname);
            ps.setString(3,uname);
            ps.setString(4, password);
            ps.setString(5, contact_no);
           int i = ps.executeUpdate();
           if(i>0){
               JOptionPane.showMessageDialog(this, "record inserted");
           }
           else{
               JOptionPane.showMessageDialog(this,"record not inserted");
           }
            
        }
        catch(Exception e){
            
            e.printStackTrace();
        }
    }
        
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_contactnumber = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmpassword = new javax.swing.JPasswordField();
        btn_signup = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        lbl_password_error = new javax.swing.JLabel();
        lbl_contact_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-55.png"))); // NOI18N
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 211, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Firstname :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 29, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Lastname :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 73, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Username :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 117, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 161, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Confirm Password :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 205, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Contact Number :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 249, -1, -1));
        jPanel2.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 33, 145, -1));
        jPanel2.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 77, 145, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 121, 145, -1));

        txt_contactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactnumberActionPerformed(evt);
            }
        });
        txt_contactnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contactnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contactnumberKeyReleased(evt);
            }
        });
        jPanel2.add(txt_contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 253, 145, -1));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 165, 145, -1));

        txt_confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txt_confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 209, 145, -1));

        btn_signup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-group-woman-man-48.png"))); // NOI18N
        btn_signup.setText("Signup");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-48.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        lbl_password_error.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lbl_password_error.setForeground(new java.awt.Color(255, 51, 102));
        jPanel2.add(lbl_password_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 161, 212, 26));

        lbl_contact_error.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lbl_contact_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 249, 180, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton2ActionPerformed
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt){
    login Login = new login();
        Login.setVisible(true);
        this.dispose();
    }
    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
      if(validation()){
          insertDetails();
      }
        
        
        
        /* try{
            String fname = txt_firstname.getText();
       String lname = txt_lastname.getText();
        String uname=txt_username.getText();
       String password= String.valueOf(txt_password.getText());
        String con_pass=String.valueOf(txt_confirmpassword.getText());
        String contact_no=txt_contactnumber.getText();
        
       
            
           Class.forName ("com.mysql.jdbc.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost/employee","root","");
             java.sql.PreparedStatement ps=con1.prepareStatement("insert into signup(fname,lname,uname,password,contact_no)values(?,?,?,?,?)");
            
            ps.setString(1,fname);
            ps.setString(2,lname);  
             ps.setString(3,uname);  
             ps.setString(4,password); 
             ps.setString(5,contact_no); 
              JOptionPane.showMessageDialog(this,"record added");
            
             
            ps.executeUpdate();
            {
          
            
            }
            
        }
        catch(Exception ex){
           // Logger.getLogger(TalkToRightPpl.class.getName()).log(Level.SEVERE, null, ex);
         Logger.getLogger(TalkToRightPpl.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btn_signupActionPerformed

    private void txt_confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmpasswordActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_contactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactnumberActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
        checkPassword();
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        // TODO add your handling code here:
        checkPassword();
    }//GEN-LAST:event_txt_passwordKeyReleased

    private void txt_contactnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactnumberKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_contactnumberKeyReleased

    private void txt_contactnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactnumberKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_contactnumberKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_contact_error;
    private javax.swing.JLabel lbl_password_error;
    private javax.swing.JPasswordField txt_confirmpassword;
    private javax.swing.JTextField txt_contactnumber;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}